# Site settings
title: Abraham Abdala # the principal title
subtitle: Technical Artist - Pipeline TD
short_logo: P.
description: All things tech art
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aabdala82.github.io/" # the base hostname & protocol for your site

author:
  fullname: Abraham Abdala
  github: 
  linkedin: abraham-abdala-599b3913
  email: abdala.abe@gmail.com

disqus_name: 
g_track_id: 

markdown: kramdown

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Abraham Abdala
      author_link: <a href="https://aabdala82.github.io/">Abraham Abdala<a>
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false