# Site settings
title: Abraham Abdala
short_logo: P.
description: All things tech art
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aabdala82.github.io" # the base hostname & protocol for your site

author:
  fullname: Abraham Abdala
  github: 
  linkedin: 
  email: 

disqus_name: 
g_track_id: 

markdown: kramdown

defaults:
  -
    scope:
      path: _posts
    values:
      comments: true
      listed: true
      author: Ritij Jain
      author_link: <a href="https://ritijjain.com/">Ritij Jain<a>
  -
    scope:
      path: pages/redirects
    values:
      layout: redirect
      index: false
      listed: false